### ISSUE TITLE
Keeping temporary files

### ISSUE THREAD

**Issue by AntlerDM** [nekno/DV7toDV8#8]
Can the shell script run without deleting temporary files? Maybe a different 'mode' in the config json?

I am trying to understand the details of this and would like to look at the temp files to see how it works.

**Comment by nekno** [comment]
I'll look into it, but it may not be that simple. The Platypus app that's used to bundle the scripts into an app doesn't make it easy to take input options, so I'd likely have to use another Apple Script dialog.

Since this is an unusual edge case, would you feel comfortable running the app from Terminal with a command-line option?

**Comment by AntlerDM** [comment]
That would be perfect. I'm using the command line, not the app.

**Comment by nekno** [comment]
Hi @AntlerDM — I added support for a new `--keep-files` option that you can use to keep all the intermediate files generated during processing.

`./DV7toDV8.sh --keep-files "~/Movies/Folder with MKVs"`

**Comment by AntlerDM** [comment]
Thanks very much.
